[package]
name = "prj_lcd_test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "firmware_rust"
path = "src/main.rs"

[dependencies]
gd32vf103-hal = { path = "../crates/gd32vf103-hal" }
longan-nano-bsp = { path = "../crates/longan-nano-bsp" }
embedded-hal = "1.0"
panic-halt = "0.2"
riscv-rt = "0.12"
